# Generated by Django 4.1.1 on 2022-09-28 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sentence',
            old_name='sentence',
            new_name='ar_sentence',
        ),
        migrations.AddField(
            model_name='groups',
            name='ar_name',
            field=models.CharField(default=' ', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='groups',
            name='en_name',
            field=models.CharField(default=' ', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sentence',
            name='en_sentence',
            field=models.CharField(default=' ', max_length=1000),
            preserve_default=False,
        ),
    ]
