# Generated by Django 4.1.1 on 2022-10-07 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_groups_words'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='forbidden_words',
            field=models.ManyToManyField(blank=True, null=True, to='pages.words'),
        ),
        migrations.AlterField(
            model_name='users',
            name='word_groups',
            field=models.ManyToManyField(blank=True, null=True, to='pages.groups'),
        ),
        migrations.CreateModel(
            name='answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('right', models.BooleanField()),
                ('entry_date', models.DateTimeField(auto_now_add=True)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.words')),
            ],
        ),
    ]
