# Generated by Django 4.1.1 on 2022-10-07 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_users_forbidden_words_alter_users_word_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='user',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='pages.users'),
            preserve_default=False,
        ),
    ]
