# Generated by Django 4.1.1 on 2022-10-12 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_answer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.groups'),
        ),
        migrations.AlterField(
            model_name='groups',
            name='words',
            field=models.ManyToManyField(to='pages.words'),
        ),
        migrations.AlterField(
            model_name='users',
            name='forbidden_words',
            field=models.ManyToManyField(to='pages.words'),
        ),
        migrations.AlterField(
            model_name='users',
            name='word_groups',
            field=models.ManyToManyField(to='pages.groups'),
        ),
    ]
