# Generated by Django 4.1.1 on 2022-10-13 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_answer_group_alter_groups_words_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='forbidden_words',
        ),
        migrations.CreateModel(
            name='pass_word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.groups')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.users')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.words')),
            ],
        ),
    ]
