# Generated by Django 4.1.1 on 2022-10-20 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_remove_users_forbidden_words_pass_word'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='professional',
            field=models.BooleanField(default=0),
        ),
    ]
