# Generated by Django 4.1.1 on 2022-10-20 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_groups_professional'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='img',
            field=models.ImageField(default='e', upload_to=''),
            preserve_default=False,
        ),
    ]
