# Generated by Django 4.1.1 on 2022-10-28 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_groups_book_alter_groups_words'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentence',
            name='audio_dir',
            field=models.CharField(default=' ', max_length=1000),
            preserve_default=False,
        ),
    ]
